//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dinamo
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientSet
    {
        public int ID { get; set; }
        public string ClientName { get; set; }
        public string ClientAdress { get; set; }
        public string ClientPhone { get; set; }
        public string ClientEmail { get; set; }
        public string ClientRequisits { get; set; }
    }
}
