//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dinamo
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductSet
    {
        public int ID { get; set; }
        public string ProductName { get; set; }
        public Nullable<double> ProductPrice { get; set; }
        public string Unit { get; set; }
        public Nullable<int> Remains { get; set; }
        public Nullable<int> IDSupplier { get; set; }
    
        public virtual SupplierSet SupplierSet { get; set; }
    }
}
